### ISSUE TITLE
ERROR: numba 0.54.0 has requirement numpy<1.21,>=1.17, but you'll have numpy 1.21.2 which is incompatible.

### ISSUE THREAD

**Issue by fe01134** [ibm-watson-iot/functions#435]
I created a clean virtual environment using `Python v3.7.6`

Doing a  `pip install git+git://github.com/ibm-watson-iot/functions@production --upgrade `

Get an error
`ERROR: numba 0.54.0 has requirement numpy<1.21,>=1.17, but you'll have numpy 1.21.2 which is incompatible.
`

**Comment by ankit-jha** [comment]
What's the pip version ?
pip version below 21 are more relaxed on version compliance.

**Comment by fe01134** [comment]
This is using the requirements.txt from this repo so I believe the requirements.txt needs to specify non conflicting libraries.   We also need to know what version this requirements.txt is for MAS v8.2 .. MAS V8.3  .. MAS V8.5

**Comment by herleraja** [comment]
lets use https://github.ibm.com/wiotp/Maximo-Asset-Monitor/issues for issue creation.
